name: Testing

on:
  push:
    branches: ["*"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pytest-with-nbmake:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v6
    - name: Setup uv project virtual environment
      env:
        UV_PYTHON: ${{ matrix.python-version }}
      uses: ./.github/actions/setup-uv
    - name: Run pytest --nbmake
      run: uv run --no-project pytest --nbmake
